
package com.omgm.speedy.eps.soap.model;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EPSProvider", targetNamespace = "http://ver01.eps.speedy.sirma.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EPSProvider {


    /**
     * 
     * @param username
     * @param password
     * @return
     *     returns com.omgm.speedy.eps.soap.model.ResultLogin
     * @throws InvalidUsernameOrPasswordException_Exception
     * @throws NoUserPermissionsException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.LoginResponse")
    public ResultLogin login(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws InvalidUsernameOrPasswordException_Exception, NoUserPermissionsException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param refreshSession
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isSessionActive", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.IsSessionActive")
    @ResponseWrapper(localName = "isSessionActiveResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.IsSessionActiveResponse")
    public boolean isSessionActive(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "refreshSession", targetNamespace = "")
        boolean refreshSession);

    /**
     * 
     * @param sessionId
     * @param date
     * @return
     *     returns java.util.List<com.omgm.speedy.eps.soap.model.ResultCourierService>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listServices", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListServices")
    @ResponseWrapper(localName = "listServicesResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListServicesResponse")
    public List<ResultCourierService> listServices(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "date", targetNamespace = "")
        XMLGregorianCalendar date)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param senderSiteId
     * @param sessionId
     * @param receiverSiteId
     * @param date
     * @return
     *     returns java.util.List<com.omgm.speedy.eps.soap.model.ResultCourierServiceExt>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listServicesForSites", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListServicesForSites")
    @ResponseWrapper(localName = "listServicesForSitesResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListServicesForSitesResponse")
    public List<ResultCourierServiceExt> listServicesForSites(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "date", targetNamespace = "")
        XMLGregorianCalendar date,
        @WebParam(name = "senderSiteId", targetNamespace = "")
        long senderSiteId,
        @WebParam(name = "receiverSiteId", targetNamespace = "")
        long receiverSiteId)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param senderSiteId
     * @param documents
     * @param sessionId
     * @param receiverSiteId
     * @param serviceTypeId
     * @param date
     * @return
     *     returns com.omgm.speedy.eps.soap.model.ResultMinMaxReal
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWeightInterval", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.GetWeightInterval")
    @ResponseWrapper(localName = "getWeightIntervalResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.GetWeightIntervalResponse")
    public ResultMinMaxReal getWeightInterval(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "serviceTypeId", targetNamespace = "")
        long serviceTypeId,
        @WebParam(name = "senderSiteId", targetNamespace = "")
        long senderSiteId,
        @WebParam(name = "receiverSiteId", targetNamespace = "")
        long receiverSiteId,
        @WebParam(name = "date", targetNamespace = "")
        XMLGregorianCalendar date,
        @WebParam(name = "documents", targetNamespace = "")
        boolean documents)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param nomenType
     * @return
     *     returns java.lang.String
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAddressNomenclature", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.GetAddressNomenclature")
    @ResponseWrapper(localName = "getAddressNomenclatureResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.GetAddressNomenclatureResponse")
    public String getAddressNomenclature(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "nomenType", targetNamespace = "")
        int nomenType)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @return
     *     returns java.util.List<com.omgm.speedy.eps.soap.model.ResultSite>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAllSites", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListAllSites")
    @ResponseWrapper(localName = "listAllSitesResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListAllSitesResponse")
    public List<ResultSite> listAllSites(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param name
     * @param type
     * @return
     *     returns java.util.List<com.omgm.speedy.eps.soap.model.ResultSite>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listSites", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListSites")
    @ResponseWrapper(localName = "listSitesResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListSitesResponse")
    public List<ResultSite> listSites(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "type", targetNamespace = "")
        String type,
        @WebParam(name = "name", targetNamespace = "")
        String name)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param filter
     * @return
     *     returns java.util.List<com.omgm.speedy.eps.soap.model.ResultSiteEx>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listSitesEx", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListSitesEx")
    @ResponseWrapper(localName = "listSitesExResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListSitesExResponse")
    public List<ResultSiteEx> listSitesEx(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "filter", targetNamespace = "")
        ParamFilterSite filter)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param siteId
     * @param sessionId
     * @return
     *     returns com.omgm.speedy.eps.soap.model.ResultSite
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSiteById", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.GetSiteById")
    @ResponseWrapper(localName = "getSiteByIdResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.GetSiteByIdResponse")
    public ResultSite getSiteById(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "siteId", targetNamespace = "")
        Long siteId)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param addrNomen
     * @param sessionId
     * @return
     *     returns java.util.List<com.omgm.speedy.eps.soap.model.ResultSite>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSitesByAddrNomenType", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.GetSitesByAddrNomenType")
    @ResponseWrapper(localName = "getSitesByAddrNomenTypeResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.GetSitesByAddrNomenTypeResponse")
    public List<ResultSite> getSitesByAddrNomenType(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "addrNomen", targetNamespace = "")
        AddrNomen addrNomen)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listStreetTypes", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListStreetTypes")
    @ResponseWrapper(localName = "listStreetTypesResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListStreetTypesResponse")
    public List<String> listStreetTypes(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listQuarterTypes", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListQuarterTypes")
    @ResponseWrapper(localName = "listQuarterTypesResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListQuarterTypesResponse")
    public List<String> listQuarterTypes(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param siteId
     * @param sessionId
     * @param name
     * @return
     *     returns java.util.List<com.omgm.speedy.eps.soap.model.ResultStreet>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listStreets", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListStreets")
    @ResponseWrapper(localName = "listStreetsResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListStreetsResponse")
    public List<ResultStreet> listStreets(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "siteId", targetNamespace = "")
        long siteId)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param siteId
     * @param sessionId
     * @param name
     * @return
     *     returns java.util.List<com.omgm.speedy.eps.soap.model.ResultQuarter>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listQuarters", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListQuarters")
    @ResponseWrapper(localName = "listQuartersResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListQuartersResponse")
    public List<ResultQuarter> listQuarters(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "siteId", targetNamespace = "")
        long siteId)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param siteId
     * @param sessionId
     * @param name
     * @return
     *     returns java.util.List<com.omgm.speedy.eps.soap.model.ResultCommonObject>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listCommonObjects", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListCommonObjects")
    @ResponseWrapper(localName = "listCommonObjectsResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListCommonObjectsResponse")
    public List<ResultCommonObject> listCommonObjects(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "siteId", targetNamespace = "")
        long siteId)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param siteId
     * @param sessionId
     * @param name
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listBlocks", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListBlocks")
    @ResponseWrapper(localName = "listBlocksResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListBlocksResponse")
    public List<String> listBlocks(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "siteId", targetNamespace = "")
        long siteId)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param siteId
     * @param sessionId
     * @param name
     * @return
     *     returns java.util.List<com.omgm.speedy.eps.soap.model.ResultOffice>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listOffices", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListOffices")
    @ResponseWrapper(localName = "listOfficesResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListOfficesResponse")
    public List<ResultOffice> listOffices(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "siteId", targetNamespace = "")
        Long siteId)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param clientId
     * @return
     *     returns com.omgm.speedy.eps.soap.model.ResultClientData
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClientById", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.GetClientById")
    @ResponseWrapper(localName = "getClientByIdResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.GetClientByIdResponse")
    public ResultClientData getClientById(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "clientId", targetNamespace = "")
        long clientId)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param clientQuery
     * @param sessionId
     * @return
     *     returns java.util.List<com.omgm.speedy.eps.soap.model.ResultClientData>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchClients", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.SearchClients")
    @ResponseWrapper(localName = "searchClientsResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.SearchClientsResponse")
    public List<ResultClientData> searchClients(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "clientQuery", targetNamespace = "")
        ParamClientSearch clientQuery)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param picking
     * @param sessionId
     * @return
     *     returns com.omgm.speedy.eps.soap.model.ResultBOL
     * @throws InvalidSessionException_Exception
     * @throws PickingValidationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createBillOfLading", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.CreateBillOfLading")
    @ResponseWrapper(localName = "createBillOfLadingResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.CreateBillOfLadingResponse")
    public ResultBOL createBillOfLading(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "picking", targetNamespace = "")
        ParamPicking picking)
        throws InvalidSessionException_Exception, PickingValidationException_Exception
    ;

    /**
     * 
     * @param includeAutoPrintJS
     * @param sessionId
     * @param billOfLading
     * @return
     *     returns byte[]
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createBillOfLadingPDF", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.CreateBillOfLadingPDF")
    @ResponseWrapper(localName = "createBillOfLadingPDFResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.CreateBillOfLadingPDFResponse")
    public byte[] createBillOfLadingPDF(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "billOfLading", targetNamespace = "")
        long billOfLading,
        @WebParam(name = "includeAutoPrintJS", targetNamespace = "")
        boolean includeAutoPrintJS)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param picking
     * @param sessionId
     * @return
     *     returns com.omgm.speedy.eps.soap.model.ResultBOL
     * @throws InvalidSessionException_Exception
     * @throws PickingValidationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateBillOfLading", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.UpdateBillOfLading")
    @ResponseWrapper(localName = "updateBillOfLadingResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.UpdateBillOfLadingResponse")
    public ResultBOL updateBillOfLading(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "picking", targetNamespace = "")
        ParamPicking picking)
        throws InvalidSessionException_Exception, PickingValidationException_Exception
    ;

    /**
     * 
     * @param order
     * @param sessionId
     * @return
     *     returns java.util.List<com.omgm.speedy.eps.soap.model.ResultOrderPickingInfo>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createOrder", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.CreateOrder")
    @ResponseWrapper(localName = "createOrderResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.CreateOrderResponse")
    public List<ResultOrderPickingInfo> createOrder(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "order", targetNamespace = "")
        ParamOrder order)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param parcelId
     * @param sessionId
     * @return
     *     returns byte[]
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createCustomTravelLabelPDFType1", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.CreateCustomTravelLabelPDFType1")
    @ResponseWrapper(localName = "createCustomTravelLabelPDFType1Response", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.CreateCustomTravelLabelPDFType1Response")
    public byte[] createCustomTravelLabelPDFType1(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "parcelId", targetNamespace = "")
        long parcelId)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param params
     * @return
     *     returns byte[]
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPDF", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.CreatePDF")
    @ResponseWrapper(localName = "createPDFResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.CreatePDFResponse")
    public byte[] createPDF(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "params", targetNamespace = "")
        ParamPDF params)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param calculation
     * @param sessionId
     * @return
     *     returns com.omgm.speedy.eps.soap.model.ResultCalculation
     * @throws InvalidSessionException_Exception
     * @throws PickingValidationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculate", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.Calculate")
    @ResponseWrapper(localName = "calculateResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.CalculateResponse")
    public ResultCalculation calculate(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "calculation", targetNamespace = "")
        ParamCalculation calculation)
        throws InvalidSessionException_Exception, PickingValidationException_Exception
    ;

    /**
     * 
     * @param calculation
     * @param serviceTypeIds
     * @param sessionId
     * @return
     *     returns java.util.List<com.omgm.speedy.eps.soap.model.ResultCalculationMS>
     * @throws InvalidSessionException_Exception
     * @throws PickingValidationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculateMultipleServices", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.CalculateMultipleServices")
    @ResponseWrapper(localName = "calculateMultipleServicesResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.CalculateMultipleServicesResponse")
    public List<ResultCalculationMS> calculateMultipleServices(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "calculation", targetNamespace = "")
        ParamCalculation calculation,
        @WebParam(name = "serviceTypeIds", targetNamespace = "")
        List<Long> serviceTypeIds)
        throws InvalidSessionException_Exception, PickingValidationException_Exception
    ;

    /**
     * 
     * @param picking
     * @param sessionId
     * @return
     *     returns com.omgm.speedy.eps.soap.model.ResultCalculation
     * @throws InvalidSessionException_Exception
     * @throws PickingValidationException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculatePicking", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.CalculatePicking")
    @ResponseWrapper(localName = "calculatePickingResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.CalculatePickingResponse")
    public ResultCalculation calculatePicking(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "picking", targetNamespace = "")
        ParamPicking picking)
        throws InvalidSessionException_Exception, PickingValidationException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param billOfLading
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "invalidatePicking", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.InvalidatePicking")
    @ResponseWrapper(localName = "invalidatePickingResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.InvalidatePickingResponse")
    public void invalidatePicking(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "billOfLading", targetNamespace = "")
        long billOfLading)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param parcel
     * @param sessionId
     * @return
     *     returns long
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addParcel", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.AddParcel")
    @ResponseWrapper(localName = "addParcelResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.AddParcelResponse")
    public long addParcel(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "parcel", targetNamespace = "")
        ParamParcel parcel)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param billOfLading
     * @return
     *     returns com.omgm.speedy.eps.soap.model.ResultBOL
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "finalizeBillOfLadingCreation", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.FinalizeBillOfLadingCreation")
    @ResponseWrapper(localName = "finalizeBillOfLadingCreationResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.FinalizeBillOfLadingCreationResponse")
    public ResultBOL finalizeBillOfLadingCreation(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "billOfLading", targetNamespace = "")
        long billOfLading)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param senderOfficeId
     * @param senderSiteId
     * @param sessionId
     * @param serviceTypeId
     * @param minDate
     * @return
     *     returns java.util.List<javax.xml.datatype.XMLGregorianCalendar>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllowedDaysForTaking", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.GetAllowedDaysForTaking")
    @ResponseWrapper(localName = "getAllowedDaysForTakingResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.GetAllowedDaysForTakingResponse")
    public List<XMLGregorianCalendar> getAllowedDaysForTaking(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "serviceTypeId", targetNamespace = "")
        long serviceTypeId,
        @WebParam(name = "senderSiteId", targetNamespace = "")
        Long senderSiteId,
        @WebParam(name = "senderOfficeId", targetNamespace = "")
        Long senderOfficeId,
        @WebParam(name = "minDate", targetNamespace = "")
        XMLGregorianCalendar minDate)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param billOfLading
     * @return
     *     returns java.util.List<com.omgm.speedy.eps.soap.model.ResultParcelInfo>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPickingParcels", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.GetPickingParcels")
    @ResponseWrapper(localName = "getPickingParcelsResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.GetPickingParcelsResponse")
    public List<ResultParcelInfo> getPickingParcels(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "billOfLading", targetNamespace = "")
        long billOfLading)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param billOfLading
     * @return
     *     returns java.util.List<com.omgm.speedy.eps.soap.model.ResultTrackPicking>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "trackPicking", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.TrackPicking")
    @ResponseWrapper(localName = "trackPickingResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.TrackPickingResponse")
    public List<ResultTrackPicking> trackPicking(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "billOfLading", targetNamespace = "")
        long billOfLading)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param language
     * @param billOfLading
     * @return
     *     returns java.util.List<com.omgm.speedy.eps.soap.model.ResultTrackPickingEx>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "trackPickingEx", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.TrackPickingEx")
    @ResponseWrapper(localName = "trackPickingExResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.TrackPickingExResponse")
    public List<ResultTrackPickingEx> trackPickingEx(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "billOfLading", targetNamespace = "")
        long billOfLading,
        @WebParam(name = "language", targetNamespace = "")
        ParamLanguage language)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param parcelId
     * @param sessionId
     * @param language
     * @return
     *     returns java.util.List<com.omgm.speedy.eps.soap.model.ResultTrackPickingEx>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "trackParcel", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.TrackParcel")
    @ResponseWrapper(localName = "trackParcelResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.TrackParcelResponse")
    public List<ResultTrackPickingEx> trackParcel(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "parcelId", targetNamespace = "")
        long parcelId,
        @WebParam(name = "language", targetNamespace = "")
        ParamLanguage language)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param params
     * @return
     *     returns java.util.List<java.lang.Long>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchPickingsByRefNumber", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.SearchPickingsByRefNumber")
    @ResponseWrapper(localName = "searchPickingsByRefNumberResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.SearchPickingsByRefNumberResponse")
    public List<Long> searchPickingsByRefNumber(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "params", targetNamespace = "")
        ParamSearchByRefNum params)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param address
     * @param sessionId
     * @return
     *     returns java.util.List<com.omgm.speedy.eps.soap.model.ResultAddressSearch>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addressSearch", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.AddressSearch")
    @ResponseWrapper(localName = "addressSearchResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.AddressSearchResponse")
    public List<ResultAddressSearch> addressSearch(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "address", targetNamespace = "")
        ParamAddressSearch address)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param coordY
     * @param coordX
     * @return
     *     returns long
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMicroregionId", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.GetMicroregionId")
    @ResponseWrapper(localName = "getMicroregionIdResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.GetMicroregionIdResponse")
    public long getMicroregionId(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "coordX", targetNamespace = "")
        double coordX,
        @WebParam(name = "coordY", targetNamespace = "")
        double coordY)
        throws InvalidSessionException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @return
     *     returns java.util.List<com.omgm.speedy.eps.soap.model.ResultSpecialDeliveryRequirement>
     * @throws InvalidSessionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listSpecialDeliveryRequirements", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListSpecialDeliveryRequirements")
    @ResponseWrapper(localName = "listSpecialDeliveryRequirementsResponse", targetNamespace = "http://ver01.eps.speedy.sirma.com/", className = "com.omgm.speedy.eps.soap.model.ListSpecialDeliveryRequirementsResponse")
    @Action(input = "http://ver01.eps.speedy.sirma.com/EPSProvider/listSpecialDeliveryRequirementsRequest", output = "http://ver01.eps.speedy.sirma.com/EPSProvider/listSpecialDeliveryRequirementsResponse", fault = {
        @FaultAction(className = InvalidSessionException_Exception.class, value = "http://ver01.eps.speedy.sirma.com/EPSProvider/listSpecialDeliveryRequirements/Fault/InvalidSessionException")
    })
    public List<ResultSpecialDeliveryRequirement> listSpecialDeliveryRequirements(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId)
        throws InvalidSessionException_Exception
    ;
}
