
package com.omgm.speedy.eps.soap.model;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidUsernameOrPasswordException", targetNamespace = "http://ver01.eps.speedy.sirma.com/")
public class InvalidUsernameOrPasswordException_Exception
    extends Exception
{

 	private static final long serialVersionUID = 1L;
 	
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidUsernameOrPasswordException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public InvalidUsernameOrPasswordException_Exception(String message, InvalidUsernameOrPasswordException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public InvalidUsernameOrPasswordException_Exception(String message, InvalidUsernameOrPasswordException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.omgm.speedy.eps.soap.model.InvalidUsernameOrPasswordException
     */
    public InvalidUsernameOrPasswordException getFaultInfo() {
        return faultInfo;
    }

}
