
package com.omgm.speedy.eps.soap.model;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PickingValidationException", targetNamespace = "http://ver01.eps.speedy.sirma.com/")
public class PickingValidationException_Exception
    extends Exception
{

	private static final long serialVersionUID = 1L;
	
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PickingValidationException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public PickingValidationException_Exception(String message, PickingValidationException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public PickingValidationException_Exception(String message, PickingValidationException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.omgm.speedy.eps.soap.model.PickingValidationException
     */
    public PickingValidationException getFaultInfo() {
        return faultInfo;
    }

}
