
package com.omgm.speedy.eps.soap.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pickingValidationErrorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="pickingValidationErrorType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="COMMON_ERROR"/>
 *     &lt;enumeration value="AMOUNT_INSURANCE_OUT_OF_RANGE"/>
 *     &lt;enumeration value="AMOUNT_CASH_ON_DELIVERY_OUT_OF_RANGE"/>
 *     &lt;enumeration value="AMOUNT_MONEY_TRANSFER_REQ_OUT_OF_RANGE"/>
 *     &lt;enumeration value="MONEY_TRANSFER_NOT_ALLOWED"/>
 *     &lt;enumeration value="SENDER_HAS_NO_ANNEX_FOR_CASH_ON_DELIVERY"/>
 *     &lt;enumeration value="INSURANCE_CANNOT_BE_LESS_THAN_CASH_ON_DELIVERY"/>
 *     &lt;enumeration value="WEIGHT_NOT_IN_RANGE"/>
 *     &lt;enumeration value="DOCUMENTS_NOT_ALLOWED_FOR_THIS_SERVICE_AND_SITES"/>
 *     &lt;enumeration value="DOCUMENT_PICKINGS_CAN_CONSIST_OF_ONLY_ONE_PARCEL"/>
 *     &lt;enumeration value="DOCUMENT_PICKINGS_ARE_NOT_ALLOWED_TO_HAVE_INSURANCE"/>
 *     &lt;enumeration value="DOCUMENT_PICKINGS_CANNOT_BE_PALLETIZED"/>
 *     &lt;enumeration value="FIXED_TIME_DELIVERY_NOT_ALLOWED_FOR_RECEIVER_SITE"/>
 *     &lt;enumeration value="FIXED_TIME_DELIVERY_NOT_ALLOWED_FOR_SERVICE"/>
 *     &lt;enumeration value="INVALID_FIXED_TIME_FOR_DELIVERY"/>
 *     &lt;enumeration value="NO_MORE_THAN_3_PHONE_NUMBERS_EXPECTED"/>
 *     &lt;enumeration value="INVALID_PHONE_NUMBER"/>
 *     &lt;enumeration value="LOGGED_CLIENT_OBJECT_MUST_BE_PAYER_OR_SENDER"/>
 *     &lt;enumeration value="INVALID_PARCELS_INFO"/>
 *     &lt;enumeration value="INVALID_TAKING_DATE"/>
 *     &lt;enumeration value="INVALID_RET_TO_CLIENT_ID"/>
 *     &lt;enumeration value="REQUIRED_BRINGING_TO_OFFICE"/>
 *     &lt;enumeration value="INVALID_PALLET_SIZE"/>
 *     &lt;enumeration value="INVALID_PALLET_WEIGHT"/>
 *     &lt;enumeration value="INVALID_PARCEL_ID"/>
 *     &lt;enumeration value="INVALID_EMAIL"/>
 *     &lt;enumeration value="INVALID_RETURN_SHIPMENT_REQUEST"/>
 *     &lt;enumeration value="INVALID_RETURN_SERVICE_REQUEST"/>
 *     &lt;enumeration value="SERVICE_NOT_ALLOWED_FOR_OFFICE_BTO"/>
 *     &lt;enumeration value="SERVICE_NOT_ALLOWED_FOR_OFFICE_TBC"/>
 *     &lt;enumeration value="DELIVERY_FROM_ADDRESS_TO_ADDRESS_NOT_ALLOWED"/>
 *     &lt;enumeration value="DELIVERY_FROM_ADDRESS_TO_OFFICE_NOT_ALLOWED"/>
 *     &lt;enumeration value="DELIVERY_FROM_OFFICE_TO_ADDRESS_NOT_ALLOWED"/>
 *     &lt;enumeration value="DELIVERY_FROM_OFFICE_TO_OFFICE_NOT_ALLOWED"/>
 *     &lt;enumeration value="NON_WORKING_DAY_FOR_SELECTED_OFFICE_TBC"/>
 *     &lt;enumeration value="NON_WORKING_DAY_FOR_SELECTED_OFFICE_BTO"/>
 *     &lt;enumeration value="NON_ACTIVE_OFFICE_TBC"/>
 *     &lt;enumeration value="NON_ACTIVE_OFFICE_BTO"/>
 *     &lt;enumeration value="FOREIGN_PARCEL_NUMBER_ERROR"/>
 *     &lt;enumeration value="MISSING_REQUIRED_VALUE_FIXED_TIME_FOR_DELIVERY"/>
 *     &lt;enumeration value="MISSING_REQUIRED_VALUE_CONTENTS"/>
 *     &lt;enumeration value="MISSING_REQUIRED_VALUE_PACKING"/>
 *     &lt;enumeration value="MISSING_REQUIRED_VALUE_PARTNER_NAME"/>
 *     &lt;enumeration value="MISSING_REQUIRED_VALUE_ADDRESS"/>
 *     &lt;enumeration value="MISSING_REQUIRED_VALUE_PHONE_SENDER"/>
 *     &lt;enumeration value="MISSING_REQUIRED_VALUE_PHONE_RECEIVER"/>
 *     &lt;enumeration value="MISSING_REQUIRED_VALUE_BOL"/>
 *     &lt;enumeration value="MISSING_REQUIRED_VALUE_WEIGHT_DECLARED"/>
 *     &lt;enumeration value="MISSING_REQUIRED_VALUE_PARCELS"/>
 *     &lt;enumeration value="VALUE_OUT_OF_RANGE_PARCEL_COUNT"/>
 *     &lt;enumeration value="VALUE_OUT_OF_RANGE_SIZE"/>
 *     &lt;enumeration value="VALUE_OUT_OF_RANGE_PACK_ID"/>
 *     &lt;enumeration value="VALUE_OUT_OF_RANGE_CONTENTS"/>
 *     &lt;enumeration value="VALUE_OUT_OF_RANGE_PACKING"/>
 *     &lt;enumeration value="VALUE_OUT_OF_RANGE_NOTE_CLIENT"/>
 *     &lt;enumeration value="VALUE_OUT_OF_RANGE_CLIENT_FIELD"/>
 *     &lt;enumeration value="VALUE_OUT_OF_RANGE_ADDRESS_FIELD"/>
 *     &lt;enumeration value="VALUE_OUT_OF_RANGE_REF1"/>
 *     &lt;enumeration value="VALUE_OUT_OF_RANGE_REF2"/>
 *     &lt;enumeration value="VALUE_OUT_OF_RANGE_DEFERRED_DELIVERY_WORK_DAYS"/>
 *     &lt;enumeration value="OFFICE_BTO_NOT_ALLOWED_FOR_SHIPMENT"/>
 *     &lt;enumeration value="OFFICE_TBC_NOT_ALLOWED_FOR_SHIPMENT"/>
 *     &lt;enumeration value="INVALID_WEIGHT_OR_SIZE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "pickingValidationErrorType")
@XmlEnum
public enum PickingValidationErrorType {

    COMMON_ERROR("COMMON_ERROR"),
    AMOUNT_INSURANCE_OUT_OF_RANGE("AMOUNT_INSURANCE_OUT_OF_RANGE"),
    AMOUNT_CASH_ON_DELIVERY_OUT_OF_RANGE("AMOUNT_CASH_ON_DELIVERY_OUT_OF_RANGE"),
    AMOUNT_MONEY_TRANSFER_REQ_OUT_OF_RANGE("AMOUNT_MONEY_TRANSFER_REQ_OUT_OF_RANGE"),
    MONEY_TRANSFER_NOT_ALLOWED("MONEY_TRANSFER_NOT_ALLOWED"),
    SENDER_HAS_NO_ANNEX_FOR_CASH_ON_DELIVERY("SENDER_HAS_NO_ANNEX_FOR_CASH_ON_DELIVERY"),
    INSURANCE_CANNOT_BE_LESS_THAN_CASH_ON_DELIVERY("INSURANCE_CANNOT_BE_LESS_THAN_CASH_ON_DELIVERY"),
    WEIGHT_NOT_IN_RANGE("WEIGHT_NOT_IN_RANGE"),
    DOCUMENTS_NOT_ALLOWED_FOR_THIS_SERVICE_AND_SITES("DOCUMENTS_NOT_ALLOWED_FOR_THIS_SERVICE_AND_SITES"),
    DOCUMENT_PICKINGS_CAN_CONSIST_OF_ONLY_ONE_PARCEL("DOCUMENT_PICKINGS_CAN_CONSIST_OF_ONLY_ONE_PARCEL"),
    DOCUMENT_PICKINGS_ARE_NOT_ALLOWED_TO_HAVE_INSURANCE("DOCUMENT_PICKINGS_ARE_NOT_ALLOWED_TO_HAVE_INSURANCE"),
    DOCUMENT_PICKINGS_CANNOT_BE_PALLETIZED("DOCUMENT_PICKINGS_CANNOT_BE_PALLETIZED"),
    FIXED_TIME_DELIVERY_NOT_ALLOWED_FOR_RECEIVER_SITE("FIXED_TIME_DELIVERY_NOT_ALLOWED_FOR_RECEIVER_SITE"),
    FIXED_TIME_DELIVERY_NOT_ALLOWED_FOR_SERVICE("FIXED_TIME_DELIVERY_NOT_ALLOWED_FOR_SERVICE"),
    INVALID_FIXED_TIME_FOR_DELIVERY("INVALID_FIXED_TIME_FOR_DELIVERY"),
    NO_MORE_THAN_3_PHONE_NUMBERS_EXPECTED("NO_MORE_THAN_3_PHONE_NUMBERS_EXPECTED"),
    INVALID_PHONE_NUMBER("INVALID_PHONE_NUMBER"),
    LOGGED_CLIENT_OBJECT_MUST_BE_PAYER_OR_SENDER("LOGGED_CLIENT_OBJECT_MUST_BE_PAYER_OR_SENDER"),
    INVALID_PARCELS_INFO("INVALID_PARCELS_INFO"),
    INVALID_TAKING_DATE("INVALID_TAKING_DATE"),
    INVALID_RET_TO_CLIENT_ID("INVALID_RET_TO_CLIENT_ID"),
    REQUIRED_BRINGING_TO_OFFICE("REQUIRED_BRINGING_TO_OFFICE"),
    INVALID_PALLET_SIZE("INVALID_PALLET_SIZE"),
    INVALID_PALLET_WEIGHT("INVALID_PALLET_WEIGHT"),
    INVALID_PARCEL_ID("INVALID_PARCEL_ID"),
    INVALID_EMAIL("INVALID_EMAIL"),
    INVALID_RETURN_SHIPMENT_REQUEST("INVALID_RETURN_SHIPMENT_REQUEST"),
    INVALID_RETURN_SERVICE_REQUEST("INVALID_RETURN_SERVICE_REQUEST"),
    SERVICE_NOT_ALLOWED_FOR_OFFICE_BTO("SERVICE_NOT_ALLOWED_FOR_OFFICE_BTO"),
    SERVICE_NOT_ALLOWED_FOR_OFFICE_TBC("SERVICE_NOT_ALLOWED_FOR_OFFICE_TBC"),
    DELIVERY_FROM_ADDRESS_TO_ADDRESS_NOT_ALLOWED("DELIVERY_FROM_ADDRESS_TO_ADDRESS_NOT_ALLOWED"),
    DELIVERY_FROM_ADDRESS_TO_OFFICE_NOT_ALLOWED("DELIVERY_FROM_ADDRESS_TO_OFFICE_NOT_ALLOWED"),
    DELIVERY_FROM_OFFICE_TO_ADDRESS_NOT_ALLOWED("DELIVERY_FROM_OFFICE_TO_ADDRESS_NOT_ALLOWED"),
    DELIVERY_FROM_OFFICE_TO_OFFICE_NOT_ALLOWED("DELIVERY_FROM_OFFICE_TO_OFFICE_NOT_ALLOWED"),
    NON_WORKING_DAY_FOR_SELECTED_OFFICE_TBC("NON_WORKING_DAY_FOR_SELECTED_OFFICE_TBC"),
    NON_WORKING_DAY_FOR_SELECTED_OFFICE_BTO("NON_WORKING_DAY_FOR_SELECTED_OFFICE_BTO"),
    NON_ACTIVE_OFFICE_TBC("NON_ACTIVE_OFFICE_TBC"),
    NON_ACTIVE_OFFICE_BTO("NON_ACTIVE_OFFICE_BTO"),
    FOREIGN_PARCEL_NUMBER_ERROR("FOREIGN_PARCEL_NUMBER_ERROR"),
    MISSING_REQUIRED_VALUE_FIXED_TIME_FOR_DELIVERY("MISSING_REQUIRED_VALUE_FIXED_TIME_FOR_DELIVERY"),
    MISSING_REQUIRED_VALUE_CONTENTS("MISSING_REQUIRED_VALUE_CONTENTS"),
    MISSING_REQUIRED_VALUE_PACKING("MISSING_REQUIRED_VALUE_PACKING"),
    MISSING_REQUIRED_VALUE_PARTNER_NAME("MISSING_REQUIRED_VALUE_PARTNER_NAME"),
    MISSING_REQUIRED_VALUE_ADDRESS("MISSING_REQUIRED_VALUE_ADDRESS"),
    MISSING_REQUIRED_VALUE_PHONE_SENDER("MISSING_REQUIRED_VALUE_PHONE_SENDER"),
    MISSING_REQUIRED_VALUE_PHONE_RECEIVER("MISSING_REQUIRED_VALUE_PHONE_RECEIVER"),
    MISSING_REQUIRED_VALUE_BOL("MISSING_REQUIRED_VALUE_BOL"),
    MISSING_REQUIRED_VALUE_WEIGHT_DECLARED("MISSING_REQUIRED_VALUE_WEIGHT_DECLARED"),
    MISSING_REQUIRED_VALUE_PARCELS("MISSING_REQUIRED_VALUE_PARCELS"),
    VALUE_OUT_OF_RANGE_PARCEL_COUNT("VALUE_OUT_OF_RANGE_PARCEL_COUNT"),
    VALUE_OUT_OF_RANGE_SIZE("VALUE_OUT_OF_RANGE_SIZE"),
    VALUE_OUT_OF_RANGE_PACK_ID("VALUE_OUT_OF_RANGE_PACK_ID"),
    VALUE_OUT_OF_RANGE_CONTENTS("VALUE_OUT_OF_RANGE_CONTENTS"),
    VALUE_OUT_OF_RANGE_PACKING("VALUE_OUT_OF_RANGE_PACKING"),
    VALUE_OUT_OF_RANGE_NOTE_CLIENT("VALUE_OUT_OF_RANGE_NOTE_CLIENT"),
    VALUE_OUT_OF_RANGE_CLIENT_FIELD("VALUE_OUT_OF_RANGE_CLIENT_FIELD"),
    VALUE_OUT_OF_RANGE_ADDRESS_FIELD("VALUE_OUT_OF_RANGE_ADDRESS_FIELD"),
    @XmlEnumValue("VALUE_OUT_OF_RANGE_REF1")
    VALUE_OUT_OF_RANGE_REF_1("VALUE_OUT_OF_RANGE_REF1"),
    @XmlEnumValue("VALUE_OUT_OF_RANGE_REF2")
    VALUE_OUT_OF_RANGE_REF_2("VALUE_OUT_OF_RANGE_REF2"),
    VALUE_OUT_OF_RANGE_DEFERRED_DELIVERY_WORK_DAYS("VALUE_OUT_OF_RANGE_DEFERRED_DELIVERY_WORK_DAYS"),
    OFFICE_BTO_NOT_ALLOWED_FOR_SHIPMENT("OFFICE_BTO_NOT_ALLOWED_FOR_SHIPMENT"),
    OFFICE_TBC_NOT_ALLOWED_FOR_SHIPMENT("OFFICE_TBC_NOT_ALLOWED_FOR_SHIPMENT"),
    INVALID_WEIGHT_OR_SIZE("INVALID_WEIGHT_OR_SIZE");
    private final String value;

    PickingValidationErrorType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PickingValidationErrorType fromValue(String v) {
        for (PickingValidationErrorType c: PickingValidationErrorType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
